# fly.toml app configuration file generated for elixir-short-url on 2023-11-02T16:07:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elixir-short-url"
primary_region = "gru"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "elixir-short-url.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
